#!/bin/bash
case "$1" in
  start|on)
	start-stop-daemon -Sbvx /usr/share/sinta/sintastart.sh
	;;
  restart|reload|force-reload)
	;;
  stop)
	;;
  *)
	start-stop-daemon -Sbvx /usr/share/sinta/sintastart.sh
	;;
esac


