ALTER TABLE WRH_PINV_PRODUCTS ADD COLUMN POSIND FLOAT;
UPDATE WRH_PINV_PRODUCTS SET POSIND=POS;
ALTER TABLE WRH_PINV_PRODUCTS ALTER COLUMN POSIND NOT NULL;
ALTER TABLE WRH_PINV_PRODUCTS DROP COLUMN POS;

SELECT * FROM APP.WRH_PINV_PRODUCTS;

UPDATE CHANGE_LOG SET CHANGE_VAL ='ALTER TABLE WRH_PINV_PRODUCTS ADD COLUMN POSIND FLOAT' WHERE ID='wrh_pinv_products__7';
UPDATE CHANGE_LOG SET CHANGE_VAL ='ALTER TABLE WRH_PINV_PRODUCTS ALTER COLUMN POSIND NOT NULL' WHERE ID='wrh_pinv_products__8';