ALTER TABLE APP.WRH_PINV_PRODUCTS ADD COLUMN PRICE_TMP DECIMAL(12,4);
UPDATE APP.WRH_PINV_PRODUCTS SET PRICE_TMP=PRICE;
ALTER TABLE APP.WRH_PINV_PRODUCTS DROP COLUMN PRICE;
ALTER TABLE APP.WRH_PINV_PRODUCTS ADD COLUMN PRICE DECIMAL(12,4);
UPDATE APP.WRH_PINV_PRODUCTS SET PRICE=PRICE_TMP;
ALTER TABLE APP.WRH_PINV_PRODUCTS DROP COLUMN PRICE_TMP;
SELECT * FROM APP.WRH_PINV_PRODUCTS;

UPDATE CHANGE_LOG SET CHANGE_VAL ='ALTER TABLE WRH_PINV_PRODUCTS ADD COLUMN PRICE DECIMAL(10,4)' WHERE ID='wrh_pinv_products_14';